name: flutter_alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.2
author: hautv.fami
homepage: https://github.com/hautvfami/flutter-alice

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  dio: ^5.1.2
  chopper: ^6.1.2
  overlay_support: ^2.1.0
  share: ^2.0.4
  rxdart: ^0.27.7
